# Generated by Django 5.2 on 2025-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_hash'], name='files_file_file_ha_868749_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['is_duplicate'], name='files_file_is_dupl_fd742f_idx'),
        ),
    ]
