# Generated by Django 4.2.20 on 2025-04-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='original_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='files.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='reference_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type'], name='files_file_file_ty_2d7e73_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size'], name='files_file_size_6009e9_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['uploaded_at'], name='files_file_uploade_726d10_idx'),
        ),
    ]
